sao-pedro descarrega aluminion doca: 0 conteineres: 50
foca descarrega feijao doca: 0 conteineres: 10
fortunas descarrega soja doca: 1 conteineres: 34
atila descarrega balxita doca: 1 conteineres: 20
vento-meu descarrega madeira doca: 1 conteineres: 6
extasis descarrega banana doca: 2 conteineres: 11
jacaranda descarrega soja doca: 2 conteineres: 30
bwana-mkubwa descarrega carvao doca: 2 conteineres: 19
abril carrega feijao doca: 0 conteineres: 10
anequim descarrega banana doca: 0 conteineres: 10
caranguejo descarrega banana doca: 3 conteineres: 15
jolly-jumper descarrega castanha doca: 3 conteineres: 10
bolina descarrega feijao doca: 3 conteineres: 35
ventosga descarrega aluminion doca: 4 conteineres: 40
vira-ventos descarrega microchips doca: 4 conteineres: 20
windsong descarrega bronze doca: 5 conteineres: 35
gap descarrega balxita doca: 5 conteineres: 25
domino carrega carvao doca: 2 conteineres: 19
hera descarrega bronze doca: 2 conteineres: 19
gipsy carrega microchips doca: 4 conteineres: 20
clip descarrega soja doca: 4 conteineres: 20
orca descarrega ouro doca: 6 conteineres: 60
foca descarrega feijao doca: 7 conteineres: 60
wind carrega balxita doca: 5 conteineres: 25
golfinho carrega banana doca: 0 conteineres: 10
celacanto carrega madeira doca: 1 conteineres: 6
vento-meu descarrega madeira doca: 0 conteineres: 10
bwana-mkubwa descarrega carvao doca: 1 conteineres: 6
abril carrega feijao doca: 3 conteineres: 35
conquilha carrega bronze doca: 2 conteineres: 19
alforreca carrega castanha doca: 3 conteineres: 10
anequim descarrega banana doca: 2 conteineres: 5
abalada carrega ouro doca: 6 conteineres: 60
bolina descarrega feijao doca: 2 conteineres: 14
vira-ventos descarrega microchips doca: 3 conteineres: 45
gap descarrega balxita doca: 5 conteineres: 21
vento-norte carrega soja doca: 4 conteineres: 20
todos-os-santos carrega aluminion doca: 4 conteineres: 30
domino carrega carvao doca: 1 conteineres: 6
hera descarrega bronze doca: 1 conteineres: 6
gipsy carrega microchips doca: 3 conteineres: 10
clip descarrega soja doca: 3 conteineres: 4
orca descarrega ouro doca: 3 conteineres: 6
foca descarrega feijao doca: 4 conteineres: 30
wind carrega balxita doca: 5 conteineres: 21
celacanto carrega madeira doca: 0 conteineres: 10
vento-meu descarrega madeira doca: 0 conteineres: 4
bwana-mkubwa descarrega carvao doca: 0 conteineres: 6
abril carrega feijao doca: 2 conteineres: 14
conquilha carrega bronze doca: 1 conteineres: 6
abalada carrega ouro doca: 3 conteineres: 6
bolina descarrega feijao doca: 1 conteineres: 6
vira-ventos descarrega microchips doca: 2 conteineres: 14
vento-norte carrega soja doca: 3 conteineres: 4
domino carrega carvao doca: 0 conteineres: 6
hera descarrega bronze doca: 0 conteineres: 6
orca descarrega ouro doca: 3 conteineres: 10
bwana-mkubwa descarrega carvao doca: 4 conteineres: 20
abril carrega feijao doca: 1 conteineres: 6
conquilha carrega bronze doca: 0 conteineres: 6
abalada carrega ouro doca: 3 conteineres: 10
ilinx carrega microchips doca: 2 conteineres: 14
bolina descarrega feijao doca: 0 conteineres: 5
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 4 conteineres: 20
hera descarrega bronze doca: 1 conteineres: 6
orca descarrega ouro doca: 2 conteineres: 4
bwana-mkubwa descarrega carvao doca: 2 conteineres: 10
abril carrega feijao doca: 4 conteineres: 30
conquilha carrega bronze doca: 1 conteineres: 6
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 2 conteineres: 10
wind carrega balxita doca: 1 conteineres: 20
spirit-of-jesus carrega aluminion doca: 4 conteineres: 10
bwana-mkubwa descarrega carvao doca: 1 conteineres: 26
abril carrega feijao doca: 7 conteineres: 60
conquilha carrega bronze doca: 5 conteineres: 35
abalada carrega ouro doca: 2 conteineres: 4
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 1 conteineres: 26
golfinho carrega banana doca: 2 conteineres: 5
bwana-mkubwa descarrega carvao doca: 1 conteineres: 26
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
vento-norte carrega soja doca: 2 conteineres: 30
domino carrega carvao doca: 1 conteineres: 26
golfinho carrega banana doca: 2 conteineres: 11
bwana-mkubwa descarrega carvao doca: 1 conteineres: 26
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 1 conteineres: 26
bwana-mkubwa descarrega carvao doca: 1 conteineres: 26
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 1 conteineres: 26
bwana-mkubwa descarrega carvao doca: 1 conteineres: 26
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 1 conteineres: 26
bwana-mkubwa descarrega carvao doca: 1 conteineres: 9
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
domino carrega carvao doca: 1 conteineres: 9
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
vento-norte carrega soja doca: 1 conteineres: 34
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
vira-ventos descarrega microchips doca: 0 conteineres: 1
ilinx carrega microchips doca: 0 conteineres: 1
abril carrega feijao doca: 0 conteineres: 5
ilinx carrega microchips doca: 3 conteineres: 35
golfinho carrega banana doca: 3 conteineres: 15
celacanto carrega madeira doca: 0 conteineres: 4
spirit-of-jesus carrega aluminion doca: 0 conteineres: 50
