albatroz descarrega ouro doca: 0 conteineres: 4
venus descarrega ferro doca: 0 conteineres: 3
polaris carrega ferro doca: 0 conteineres: 3
flamingo descarrega ouro doca: 0 conteineres: 2
venus descarrega ferro doca: 0 conteineres: 1
polaris carrega ferro doca: 0 conteineres: 1
venus descarrega ferro doca: 0 conteineres: 1
polaris carrega ferro doca: 0 conteineres: 1
venus descarrega ferro doca: 0 conteineres: 1
saturno carrega ferro doca: 0 conteineres: 1
venus descarrega ferro doca: 0 conteineres: 1
saturno carrega ferro doca: 0 conteineres: 1
pollux carrega ouro doca: 0 conteineres: 6
