castor descarrega arroz doca: 0 conteineres: 5
aquarius carrega arroz doca: 0 conteineres: 5
aries descarrega cafe doca: 0 conteineres: 6
gemini descarrega arroz doca: 1 conteineres: 6
astro carrega arroz doca: 1 conteineres: 4
altair carrega cafe doca: 0 conteineres: 4
antares descarrega cafe doca: 0 conteineres: 2
aquarius carrega arroz doca: 1 conteineres: 2
cor-caroli carrega cafe doca: 0 conteineres: 4
