luna descarrega balxita doca: 0 conteineres: 3
verus descarrega balxita doca: 0 conteineres: 2
seaowl descarrega eletronico doca: 1 conteineres: 2
wonder descarrega balxita doca: 1 conteineres: 2
venus descarrega castanha doca: 1 conteineres: 1
atlantis carrega castanha doca: 1 conteineres: 1
bacus descarrega ouro doca: 1 conteineres: 1
poseidon carrega ouro doca: 1 conteineres: 1
ikaro descarrega ouro doca: 1 conteineres: 1
neptuno descarrega ouro doca: 2 conteineres: 2
sinbad descarrega prata doca: 2 conteineres: 2
hator carrega prata doca: 2 conteineres: 2
spica descarrega prata doca: 2 conteineres: 3
stratus descarrega prata doca: 3 conteineres: 5
irina carrega balxita doca: 0 conteineres: 5
solar carrega ouro doca: 1 conteineres: 1
venus descarrega castanha doca: 0 conteineres: 5
atlantis carrega castanha doca: 0 conteineres: 2
bacus descarrega ouro doca: 0 conteineres: 2
poseidon carrega ouro doca: 0 conteineres: 2
ikaro descarrega ouro doca: 0 conteineres: 2
atlas carrega prata doca: 2 conteineres: 2
argus carrega prata doca: 2 conteineres: 1
hator carrega prata doca: 3 conteineres: 2
stratus descarrega prata doca: 1 conteineres: 1
solar carrega ouro doca: 0 conteineres: 2
venus descarrega castanha doca: 0 conteineres: 2
bacus descarrega ouro doca: 2 conteineres: 2
poseidon carrega ouro doca: 2 conteineres: 3
ikaro descarrega ouro doca: 2 conteineres: 2
argus carrega prata doca: 1 conteineres: 1
irina carrega balxita doca: 1 conteineres: 2
edith carrega eletronico doca: 1 conteineres: 2
odisseia carrega castanha doca: 0 conteineres: 2
taurus carrega castanha doca: 0 conteineres: 3
solar carrega ouro doca: 2 conteineres: 3
venus descarrega castanha doca: 0 conteineres: 2
argus carrega prata doca: 3 conteineres: 3
taurus carrega castanha doca: 0 conteineres: 2
