mondu descarrega ouro doca: 0 conteineres: 5
widow descarrega bronze doca: 1 conteineres: 3
sheriff descarrega prata doca: 1 conteineres: 1
vandal descarrega prata doca: 1 conteineres: 1
katarina descarrega bronze doca: 2 conteineres: 1
maui descarrega prata doca: 2 conteineres: 1
ornn descarrega bronze doca: 2 conteineres: 2
olaf carrega ouro doca: 0 conteineres: 3
truu carrega ouro doca: 0 conteineres: 2
inker carrega bronze doca: 2 conteineres: 2
liner descarrega ouro doca: 0 conteineres: 4
octane descarrega ferro doca: 0 conteineres: 1
ynn descarrega ferro doca: 2 conteineres: 3
helena carrega ferro doca: 0 conteineres: 1
castro carrega ferro doca: 2 conteineres: 3
serf carrega ouro doca: 0 conteineres: 3
vondu carrega prata doca: 1 conteineres: 2
orleans carrega bronze doca: 1 conteineres: 1
irina carrega bronze doca: 1 conteineres: 2
jhin carrega ouro doca: 0 conteineres: 1
ynn descarrega ferro doca: 0 conteineres: 1
helena carrega ferro doca: 0 conteineres: 1
vondu carrega prata doca: 2 conteineres: 1
irina carrega bronze doca: 2 conteineres: 1
ALERTA: impossivel esvaziar fila, restam 2 navios.
