santiago descarrega laranja doca: 0 conteineres: 20
santa-teresa descarrega madeira doca: 0 conteineres: 20
santa-monica descarrega madeira doca: 0 conteineres: 5
sao-jose descarrega banana doca: 1 conteineres: 30
todos-os-santos descarrega cafe doca: 1 conteineres: 5
atlas carrega cafe doca: 1 conteineres: 5
alforreca descarrega cafe doca: 1 conteineres: 15
anequim descarrega banana doca: 2 conteineres: 5
neptuno carrega madeira doca: 0 conteineres: 5
sao-pedro descarrega arroz doca: 0 conteineres: 5
atlantis carrega arroz doca: 0 conteineres: 5
santa-maria descarrega banana doca: 0 conteineres: 5
poseidon descarrega banana doca: 2 conteineres: 5
sao-francisco descarrega arroz doca: 2 conteineres: 20
spirit-of-jesus descarrega cafe doca: 2 conteineres: 5
odisseia carrega banana doca: 0 conteineres: 5
santa-monica descarrega madeira doca: 0 conteineres: 5
bacus carrega cafe doca: 1 conteineres: 15
nimbus carrega banana doca: 1 conteineres: 30
atlas carrega cafe doca: 2 conteineres: 5
alforreca descarrega cafe doca: 1 conteineres: 25
hator carrega arroz doca: 2 conteineres: 20
sao-pedro descarrega arroz doca: 1 conteineres: 15
stratus carrega madeira doca: 0 conteineres: 25
atlantis carrega arroz doca: 1 conteineres: 5
ikaro carrega laranja doca: 0 conteineres: 14
santa-maria descarrega banana doca: 0 conteineres: 15
odisseia carrega banana doca: 0 conteineres: 5
hator carrega arroz doca: 1 conteineres: 5
ALERTA: impossivel esvaziar fila, restam 3 navios.
