fortunas descarrega soja doca: 0 conteineres: 37
aries carrega soja doca: 0 conteineres: 37
wind descarrega cobre doca: 0 conteineres: 37
nunum carrega cobre doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 37
antares carrega ferro doca: 1 conteineres: 37
astro carrega madeira doca: 0 conteineres: 37
fortunas descarrega soja doca: 0 conteineres: 37
aries carrega soja doca: 0 conteineres: 37
wind descarrega cobre doca: 0 conteineres: 37
nunum carrega cobre doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 37
antares carrega ferro doca: 1 conteineres: 37
astro carrega madeira doca: 0 conteineres: 37
fortunas descarrega soja doca: 0 conteineres: 37
aries carrega soja doca: 0 conteineres: 26
wind descarrega cobre doca: 0 conteineres: 26
nunum carrega cobre doca: 0 conteineres: 26
gap descarrega madeira doca: 0 conteineres: 26
windsong descarrega ferro doca: 1 conteineres: 37
antares carrega ferro doca: 1 conteineres: 37
astro carrega madeira doca: 0 conteineres: 26
aquarius carrega soja doca: 0 conteineres: 11
fortunas descarrega soja doca: 0 conteineres: 9
wind descarrega cobre doca: 0 conteineres: 28
gap descarrega madeira doca: 1 conteineres: 37
windsong descarrega ferro doca: 2 conteineres: 37
antares carrega ferro doca: 2 conteineres: 9
astro carrega madeira doca: 1 conteineres: 37
obelix carrega cobre doca: 0 conteineres: 28
altair carrega ferro doca: 2 conteineres: 28
aquarius carrega soja doca: 0 conteineres: 9
wind descarrega cobre doca: 0 conteineres: 22
gap descarrega madeira doca: 0 conteineres: 15
windsong descarrega ferro doca: 1 conteineres: 37
astro carrega madeira doca: 0 conteineres: 15
obelix carrega cobre doca: 0 conteineres: 22
altair carrega ferro doca: 1 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 37
astro carrega madeira doca: 0 conteineres: 28
altair carrega ferro doca: 1 conteineres: 37
castor carrega madeira doca: 0 conteineres: 9
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 37
altair carrega ferro doca: 1 conteineres: 37
castor carrega madeira doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 37
altair carrega ferro doca: 1 conteineres: 37
castor carrega madeira doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
windsong descarrega ferro doca: 1 conteineres: 4
altair carrega ferro doca: 1 conteineres: 4
castor carrega madeira doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
castor carrega madeira doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 37
castor carrega madeira doca: 0 conteineres: 37
gap descarrega madeira doca: 0 conteineres: 26
castor carrega madeira doca: 0 conteineres: 26
