cancao-do-vento descarrega cafe doca: 0 conteineres: 50
wally descarrega ferro doca: 1 conteineres: 15
tres-penas carrega cafe doca: 0 conteineres: 30
gipsy descarrega cafe doca: 0 conteineres: 20
sao-pedro descarrega soja doca: 0 conteineres: 10
santa-teresa descarrega ferro doca: 1 conteineres: 20
ufa carrega soja doca: 0 conteineres: 10
boreas-j descarrega eletronicos doca: 0 conteineres: 10
santa-maria descarrega soja doca: 1 conteineres: 15
ilinx carrega soja doca: 1 conteineres: 15
tana descarrega cafe doca: 1 conteineres: 15
gap carrega cafe doca: 1 conteineres: 15
hera carrega ferro doca: 1 conteineres: 5
santiago carrega ferro doca: 1 conteineres: 30
cancao-do-vento descarrega cafe doca: 1 conteineres: 10
sao-francisco carrega eletronicos doca: 0 conteineres: 10
sao-pedro descarrega soja doca: 0 conteineres: 10
jacaranda carrega cafe doca: 1 conteineres: 5
ufa carrega soja doca: 0 conteineres: 10
boreas-j descarrega eletronicos doca: 0 conteineres: 10
santa-maria descarrega soja doca: 1 conteineres: 45
ilinx carrega soja doca: 1 conteineres: 5
tana descarrega cafe doca: 1 conteineres: 5
gap carrega cafe doca: 1 conteineres: 5
sao-francisco carrega eletronicos doca: 0 conteineres: 10
smile carrega soja doca: 1 conteineres: 40
sao-pedro descarrega soja doca: 0 conteineres: 10
four-winds carrega soja doca: 0 conteineres: 5
boreas-j descarrega eletronicos doca: 0 conteineres: 5
santa-maria descarrega soja doca: 1 conteineres: 30
tana descarrega cafe doca: 1 conteineres: 15
gap carrega cafe doca: 1 conteineres: 5
jolly-jumper carrega cafe doca: 1 conteineres: 10
sao-francisco carrega eletronicos doca: 0 conteineres: 5
smile carrega soja doca: 0 conteineres: 5
santa-monica carrega soja doca: 1 conteineres: 25
sao-pedro descarrega soja doca: 0 conteineres: 10
boreas-j descarrega eletronicos doca: 1 conteineres: 40
aragem carrega soja doca: 0 conteineres: 10
tana descarrega cafe doca: 0 conteineres: 5
jolly-jumper carrega cafe doca: 0 conteineres: 20
brisa carrega cafe doca: 0 conteineres: 10
varino carrega cafe doca: 0 conteineres: 15
sao-francisco carrega eletronicos doca: 1 conteineres: 15
bonanca carrega eletronicos doca: 1 conteineres: 25
smile carrega soja doca: 1 conteineres: 5
sao-pedro descarrega soja doca: 0 conteineres: 20
boreas-j descarrega eletronicos doca: 0 conteineres: 5
varino carrega cafe doca: 1 conteineres: 5
bonanca carrega eletronicos doca: 0 conteineres: 5
aragem carrega soja doca: 0 conteineres: 20
