calipso descarrega cobre doca: 0 conteineres: 10
ganso-bravo descarrega cobre doca: 0 conteineres: 10
luna carrega cobre doca: 0 conteineres: 15
libre carrega cobre doca: 0 conteineres: 5
solar descarrega ouro doca: 0 conteineres: 20
pelicano descarrega cobre doca: 1 conteineres: 10
la-licorne descarrega cafe doca: 1 conteineres: 10
albatroz descarrega ferro doca: 2 conteineres: 20
astro carrega ouro doca: 0 conteineres: 20
pollux carrega cafe doca: 1 conteineres: 10
taurus descarrega ouro doca: 0 conteineres: 20
kontiki descarrega cafe doca: 1 conteineres: 10
scorpio-e-libra descarrega banana doca: 3 conteineres: 20
jupiter carrega ferro doca: 2 conteineres: 20
polaris carrega cafe doca: 1 conteineres: 10
ganso-bravo descarrega cobre doca: 1 conteineres: 10
castor carrega ouro doca: 0 conteineres: 20
libre carrega cobre doca: 1 conteineres: 5
aquarius carrega banana doca: 3 conteineres: 10
solar descarrega ouro doca: 0 conteineres: 20
antares carrega banana doca: 3 conteineres: 10
la-licorne descarrega cafe doca: 1 conteineres: 5
astro carrega ouro doca: 0 conteineres: 20
pollux carrega cafe doca: 1 conteineres: 5
taurus descarrega ouro doca: 0 conteineres: 10
kontiki descarrega cafe doca: 0 conteineres: 10
scorpio-e-libra descarrega banana doca: 1 conteineres: 5
sirius descarrega banana doca: 2 conteineres: 20
spica descarrega ouro doca: 3 conteineres: 20
polaris carrega cafe doca: 0 conteineres: 10
castor carrega ouro doca: 0 conteineres: 10
aries carrega ouro doca: 3 conteineres: 20
solar descarrega ouro doca: 0 conteineres: 20
antares carrega banana doca: 1 conteineres: 5
la-licorne descarrega cafe doca: 1 conteineres: 5
altair carrega banana doca: 2 conteineres: 20
astro carrega ouro doca: 0 conteineres: 20
pollux carrega cafe doca: 1 conteineres: 5
kontiki descarrega cafe doca: 0 conteineres: 20
sirius descarrega banana doca: 1 conteineres: 5
spica descarrega ouro doca: 2 conteineres: 20
flamingo descarrega ferro doca: 3 conteineres: 20
polaris carrega cafe doca: 0 conteineres: 10
castor carrega ouro doca: 2 conteineres: 20
solar descarrega ouro doca: 0 conteineres: 10
antares carrega banana doca: 1 conteineres: 5
cor-caroli carrega ferro doca: 3 conteineres: 20
kontiki descarrega cafe doca: 1 conteineres: 5
sirius descarrega banana doca: 2 conteineres: 20
spica descarrega ouro doca: 3 conteineres: 20
castor carrega ouro doca: 0 conteineres: 10
aries carrega ouro doca: 3 conteineres: 20
solar descarrega ouro doca: 0 conteineres: 10
antares carrega banana doca: 2 conteineres: 10
plutao carrega cafe doca: 1 conteineres: 5
altair carrega banana doca: 2 conteineres: 10
kontiki descarrega cafe doca: 1 conteineres: 5
sirius descarrega banana doca: 2 conteineres: 5
spica descarrega ouro doca: 2 conteineres: 15
flamingo descarrega ferro doca: 3 conteineres: 10
saturno descarrega banana doca: 3 conteineres: 10
castor carrega ouro doca: 0 conteineres: 10
aries carrega ouro doca: 2 conteineres: 10
solar descarrega ouro doca: 0 conteineres: 10
plutao carrega cafe doca: 1 conteineres: 5
altair carrega banana doca: 3 conteineres: 10
orion carrega cobre doca: 1 conteineres: 15
spica descarrega ouro doca: 1 conteineres: 5
saturno descarrega banana doca: 1 conteineres: 15
pinta descarrega cafe doca: 2 conteineres: 10
venus descarrega ferro doca: 3 conteineres: 10
castor carrega ouro doca: 0 conteineres: 10
solar descarrega ouro doca: 0 conteineres: 10
plutao carrega cafe doca: 2 conteineres: 10
gemini carrega ferro doca: 3 conteineres: 20
altair carrega banana doca: 1 conteineres: 15
pinta descarrega cafe doca: 1 conteineres: 15
castor carrega ouro doca: 0 conteineres: 10
pollux carrega cafe doca: 0 conteineres: 10
pinta descarrega cafe doca: 0 conteineres: 5
castor carrega ouro doca: 2 conteineres: 5
altair carrega banana doca: 2 conteineres: 5
pollux carrega cafe doca: 0 conteineres: 5
pollux carrega cafe doca: 1 conteineres: 15
castor carrega ouro doca: 1 conteineres: 5
