vaga descarrega microchips doca: 0 conteineres: 4
sea-spirit descarrega soja doca: 0 conteineres: 7
nimbus descarrega ferro doca: 0 conteineres: 1
bom-tempo descarrega microchips doca: 1 conteineres: 4
estrela-da-tarde descarrega ferro doca: 1 conteineres: 5
alvorada descarrega microchips doca: 1 conteineres: 3
sargaco carrega microchips doca: 1 conteineres: 3
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
alvorada descarrega microchips doca: 1 conteineres: 3
sargaco carrega microchips doca: 1 conteineres: 3
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
alvorada descarrega microchips doca: 1 conteineres: 1
sargaco carrega microchips doca: 1 conteineres: 1
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
pacifico carrega ferro doca: 0 conteineres: 1
nimbus descarrega ferro doca: 0 conteineres: 1
pacifico carrega ferro doca: 0 conteineres: 1
oceanos carrega soja doca: 0 conteineres: 2
ocean carrega soja doca: 0 conteineres: 5
sargaco carrega microchips doca: 0 conteineres: 4
pacifico carrega ferro doca: 1 conteineres: 5
rochedo carrega microchips doca: 1 conteineres: 3
sargaco carrega microchips doca: 1 conteineres: 1
