windsong descarrega bronze doca: 0 conteineres: 35
clip descarrega soja doca: 0 conteineres: 24
vento-meu descarrega madeira doca: 0 conteineres: 20
hera descarrega bronze doca: 0 conteineres: 21
extasis descarrega banana doca: 1 conteineres: 11
atila descarrega balxita doca: 1 conteineres: 20
anequim descarrega banana doca: 1 conteineres: 15
vira-ventos descarrega microchips doca: 1 conteineres: 54
conquilha carrega bronze doca: 0 conteineres: 21
bwana-mkubwa descarrega carvao doca: 0 conteineres: 21
caranguejo descarrega banana doca: 2 conteineres: 15
ilinx carrega microchips doca: 1 conteineres: 54
ventosga descarrega aluminion doca: 1 conteineres: 40
orca descarrega ouro doca: 1 conteineres: 14
foca descarrega feijao doca: 2 conteineres: 85
bolina descarrega feijao doca: 3 conteineres: 60
fortunas descarrega soja doca: 3 conteineres: 34
jolly-jumper descarrega castanha doca: 3 conteineres: 6
abril carrega feijao doca: 2 conteineres: 85
gap descarrega balxita doca: 2 conteineres: 46
jacaranda descarrega soja doca: 2 conteineres: 10
vento-norte carrega soja doca: 2 conteineres: 10
sao-pedro descarrega aluminion doca: 2 conteineres: 39
spirit-of-jesus carrega aluminion doca: 2 conteineres: 39
abalada carrega ouro doca: 1 conteineres: 14
hera descarrega bronze doca: 1 conteineres: 14
domino carrega carvao doca: 0 conteineres: 21
vira-ventos descarrega microchips doca: 0 conteineres: 21
conquilha carrega bronze doca: 1 conteineres: 14
bwana-mkubwa descarrega carvao doca: 1 conteineres: 14
ilinx carrega microchips doca: 0 conteineres: 21
orca descarrega ouro doca: 0 conteineres: 21
foca descarrega feijao doca: 2 conteineres: 5
alforreca carrega castanha doca: 3 conteineres: 6
jolly-jumper descarrega castanha doca: 2 conteineres: 4
vento-norte carrega soja doca: 3 conteineres: 34
sao-pedro descarrega aluminion doca: 2 conteineres: 11
spirit-of-jesus carrega aluminion doca: 2 conteineres: 11
abalada carrega ouro doca: 0 conteineres: 21
hera descarrega bronze doca: 0 conteineres: 2
domino carrega carvao doca: 1 conteineres: 14
vira-ventos descarrega microchips doca: 0 conteineres: 19
bwana-mkubwa descarrega carvao doca: 1 conteineres: 14
ilinx carrega microchips doca: 0 conteineres: 15
orca descarrega ouro doca: 0 conteineres: 15
alforreca carrega castanha doca: 2 conteineres: 4
abril carrega feijao doca: 2 conteineres: 5
wind carrega balxita doca: 2 conteineres: 46
golfinho carrega banana doca: 2 conteineres: 15
abalada carrega ouro doca: 0 conteineres: 15
domino carrega carvao doca: 1 conteineres: 14
vira-ventos descarrega microchips doca: 0 conteineres: 15
bwana-mkubwa descarrega carvao doca: 1 conteineres: 14
orca descarrega ouro doca: 2 conteineres: 10
abril carrega feijao doca: 3 conteineres: 60
gipsy carrega microchips doca: 0 conteineres: 19
abalada carrega ouro doca: 2 conteineres: 10
domino carrega carvao doca: 1 conteineres: 14
vira-ventos descarrega microchips doca: 0 conteineres: 11
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
spirit-of-jesus carrega aluminion doca: 1 conteineres: 10
todos-os-santos carrega aluminion doca: 1 conteineres: 30
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
golfinho carrega banana doca: 1 conteineres: 15
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
wind carrega balxita doca: 1 conteineres: 20
golfinho carrega banana doca: 1 conteineres: 11
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 8
domino carrega carvao doca: 0 conteineres: 8
bwana-mkubwa descarrega carvao doca: 0 conteineres: 1
domino carrega carvao doca: 0 conteineres: 1
gipsy carrega microchips doca: 0 conteineres: 11
conquilha carrega bronze doca: 0 conteineres: 2
celacanto carrega madeira doca: 0 conteineres: 20
vento-norte carrega soja doca: 0 conteineres: 24
conquilha carrega bronze doca: 0 conteineres: 35
ALERTA: impossivel esvaziar fila, restam 3 navios.
